### PR TITLE
Added CoC & edited README

### PR DESCRIPTION
**Pull request by DanM3rcurius**
added CODE OF CONDUCT and edited the README file (layout cleaning).
This is in relation to #50

### CODE REVIEW

**Comment by DanM3rcurius** [comment]
everything except License is done. Waiting to discuss it with the team during meeting today.

**Comment by DanM3rcurius** [comment]
Cleaned up folder structure and files in main folder

**Comment by DanM3rcurius** [comment]
@stephen-rowan If you have some time, could you please double check; otherwise I'll just merge tonight and we revert back or edit 🙏🏿

**Review by stephen-rowan — APPROVED** [review]
This Code of Conduct is a great start. I would merge and continue to revise in place with SD.

I was working on an [Adagov code of conduct](https://github.com/adagovorg/adagov-documentation/blob/main/CODE_OF_CONDUCT.md). before being sidetracked this past week My initial impression was that the Contributor Covenant was too prescriptive.
Here is the [AdaGov Code of Conduct Project Board](https://github.com/adagovorg/adagov-documentation/projects/1). I used these [sources](https://github.com/adagovorg/adagov-documentation/tree/main/Documents/Reference/Code-of-Conduct).

**Comment by DanM3rcurius** [comment]
Conflict resolved!

**Pull request closed without merging**
